services:
  users_cache:
    container_name: users_cache
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${SERVER_PORT}:5001'
    networks:
      - service_network
    depends_on:
      - redis_DB

  redis_DB:
    image: redis:latest
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_data:/data
    ports:
      - '${REDIS_PORT}:6379'
    networks:
      - service_network

volumes:
  redis_data:

networks:
  service_network:
    external: true